cancel
odoo-italia/documentazione pull request #22
Opened 2021-10-22 12:28 UTC by eLBati

2021-10-22 12:28 UTC, eLBati commented
@primes2h non so se c'è già da qualche altra parte, ma vedo ancora gente tradurlo con "cancella"

2021-12-01 20:44 UTC, primes2h requested changes
@eLBati 
Grazie mille della PR!

Suggerisco giusto una piccola modifica per uniformarlo agli altri verbi presenti nei glossari.

2021-12-01 20:44 UTC, primes2h commented on traduzioni/glossari/generale.rst
> +      annullare
```suggestion
   cancel, to
      annullare
```

2021-12-02 15:33 UTC, eLBati commented
@primes2h :+1:

2021-12-02 15:38 UTC, primes2h approved these changes
Ottimo!
Grazie anche per esserti accorto che mancava nel glossario. :-)

2021-12-02 15:40 UTC, primes2h commented
@eLBati 
Faccio squash e merge?

2021-12-02 15:42 UTC, eLBati commented
> @eLBati Faccio squash e merge?

ok per me

2021-12-02 15:48 UTC, merged