[IMP] build requirements
odoo-italia/documentazione pull request #25
Opened 2022-12-09 15:13 UTC by primes2h

Aggiornati i requisiti per generare la documentazione e aggiunto il file requirements.txt.

2022-12-09 15:20 UTC, primes2h commented
Risolve #7

2022-12-11 07:47 UTC, mymage approved these changes
Go

2022-12-12 13:37 UTC, tafaRU requested changes
```
python --version
Python 3.8.10
```
`pip3 install -r documentazione/requirements.txt` ottengo il seg. errore:
```
```````Building wheels for collected packages: sphinx-patchqueue
  Building wheel for sphinx-patchqueue (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3t628qld/sphinx-patchqueue/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3t628qld/sphinx-patchqueue/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bm8kdlfi
       cwd: /tmp/pip-install-3t628qld/sphinx-patchqueue/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for sphinx-patchqueue
  Running setup.py clean for sphinx-patchqueue
Failed to build sphinx-patchqueue
```

2022-12-12 13:46 UTC, primes2h commented
> ```
> python --version
> Python 3.8.10
> ```
> 
> `pip3 install -r documentazione/requirements.txt` ottengo il seg. errore:
> 
> ```
> ```````Building wheels for collected packages: sphinx-patchqueue
>   Building wheel for sphinx-patchqueue (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /tmp/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3t628qld/sphinx-patchqueue/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3t628qld/sphinx-patchqueue/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bm8kdlfi
>        cwd: /tmp/pip-install-3t628qld/sphinx-patchqueue/
>   Complete output (6 lines):
>   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: setup.py --help [cmd1 cmd2 ...]
>      or: setup.py --help-commands
>      or: setup.py cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   ----------------------------------------
>   ERROR: Failed building wheel for sphinx-patchqueue
>   Running setup.py clean for sphinx-patchqueue
> Failed to build sphinx-patchqueue
> ```

Hai usato `python -m venv`?
Se crei il virtualenv con `virtualenv` non da nessun errore, ma ho notato che se viene usato `python -m venv` produce quell'errore (solo versione 3.8, la 3.6 ad es. funziona).

2022-12-12 13:49 UTC, tafaRU commented
> Hai usato python -m venv?

sì

2022-12-12 13:50 UTC, tafaRU commented
> Se crei il virtualenv con virtualenv non dà nessun errore

Allora lo specificherei nel README, cosa ne pensi?

2022-12-12 13:51 UTC, primes2h commented
> > Se crei il virtualenv con virtualenv non dà nessun errore
> 
> Allora lo specificherei nel README, cosa ne pensi?

Si, meglio.

2022-12-12 14:04 UTC, tafaRU commented
Ok, così funziona. Ti segnalo che però, a differenza di quanto indicato, ho dovuto creare il virtualenv con: `virtualenv -p python3 venv`.

2022-12-12 14:07 UTC, primes2h commented
> Ok, così funziona. Ti segnalo che però, a differenza di quanto indicato, ho dovuto creare il virtualenv con: `virtualenv -p python3 venv`.

Ah ok, dipende dal SO dal quale lanci il comando. 
Adesso aggiorno il README.

2022-12-12 14:20 UTC, tafaRU approved these changes

2022-12-14 13:58 UTC, OpenCode approved these changes

2022-12-14 14:02 UTC, merged