Add howto 'Come contribuire su GitHub'
odoo-italia/documentazione pull request #3
Opened 2019-03-09 15:48 UTC by tafaRU

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +Le issues vengono utilizzate per segnalare task, bug o feature di un progetto. Queste andrebbero sempre controllate ed utilizzate,
```
Queste andrebbero sempre controllate ed utilizzate,
```
Come posso utilizzare una issue?

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +Fork del repository
Non farei dei sottotitoli per una riga, dovrebbe bastare un elenco numerato così sarebbe anche più chiaro che sono operazioni da fare in sequenza

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +Supponi ad esempio di aver scovato un bug in uno dei moduli italiani e di voler proporre una correzione.
Perché è nel capitolo delle operazioni preliminari?

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +    git clone git@github.com:OCA/l10n-italy.git
Così non sta clonando il fork ma  il repository OCA

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +Attenzione, il nome del branch dovrebbe avere come prefisso sempre il numero della versione Odoo.
Perché dovrebbe?

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +* base fork: OCA(l10n-italy
```suggestion
* base repository: OCA/l10n-italy
```

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +* head fork: tuo repository
```suggestion
* head repository: mio_remote/l10n-italy
```

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +* CLA BOT per verificare la stato della tua `CLA <https://odoo-community.org/page/cla>`_
Da citare all'inizio

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +Ora che la PR è stata aperta inizia il processo di review, una vera è propria conversazione in stile social in cui potrai discutere insieme
```suggestion
Ora che la PR è stata aperta inizia il processo di review (link all'altro doc): una vera e propria conversazione in stile social in cui potrai discutere insieme
```

2019-03-10 11:00 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +Assicurati che il risultato di tutti i controlli siano positivi e tieniti pronto ad applicare le correzioni suggerite.
```suggestion
Assicurati che il risultato di tutti i controlli sia positivo e tieniti pronto ad applicare le correzioni suggerite.
```

2019-03-10 14:44 UTC, mymage commented on sviluppo/come_contribuire.rst
> +Fork del repository
Concordo sul formato dei passi da seguire e allacciandomi al commento sulla issue, visto che è uno dei due strumenti, strutturerei la pagina mettendo anche le istruzioni per la issue.

2019-03-10 14:49 UTC, mymage commented on sviluppo/come_contribuire.rst
> +Supponi ad esempio di aver scovato un bug in uno dei moduli italiani e di voler proporre una correzione.
Penso anch'io che il "Supponi ..." vada inserito nella frase introduttiva rimaneggiandola un po'.
Per quanto riguarda le operazioni preliminari suggerisco di fare un documento apposito per inserirle tutte.

2019-03-10 14:51 UTC, mymage commented on sviluppo/come_contribuire.rst
> +* CLA BOT per verificare la stato della tua `CLA <https://odoo-community.org/page/cla>`_
O meglio metterla nel documento delle operazioni prliminari?

2019-03-10 15:06 UTC, mymage reviewed
Nel nostro gruppetto abbiamo definito dei tag da anteporre al titolo del commit per identificarne l'origine:
es. [DOC] per modifica documentazione nel codice, [FIX] per i fix, [REF] per il refactoring.
Cosa ne pensate?

2019-03-10 15:06 UTC, mymage commented on sviluppo/come_contribuire.rst
> +    git commit -m "Close issue #1
```suggestion
    git commit -m "Close issue #1"
```

2019-03-11 07:57 UTC, eLBati commented on sviluppo/come_contribuire.rst
> +Attenzione, il nome del branch dovrebbe avere come prefisso sempre il numero della versione Odoo.
Ad un certo punto qualcuno aveva detto che runbot per poter creare correttamente le build aveva questo requisito, ma sarebbe da verificare

2019-03-11 08:13 UTC, eLBati commented
@mymage per i commit le linee guida OCA sono
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

Un tempo si richiedeva il prefisso, qualcuno ancora lo usa. Ma poi capitava comunque che la gente scrivesse `[FIX] test` quindi un messaggio totalmente inutile. Allora si è pensato che fosse meglio richiedere messaggi chiari, significativi e auto esplicativi

2019-03-11 08:28 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +Attenzione, il nome del branch dovrebbe avere come prefisso sempre il numero della versione Odoo.
> qualcuno aveva detto che runbot per poter creare correttamente le build 

sì quella di runbot, però, come ho verificato venerdì, non mi pare più vero. Si veda a titolo di esempio https://github.com/OCA/l10n-italy/pull/1066

Potrebbe però essere adottato come best practice. Che ne pensate?

2019-03-11 09:12 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +* CLA BOT per verificare la stato della tua `CLA <https://odoo-community.org/page/cla>`_
L'operazione di firmare la CLA è già stata inserita su https://www.odoo-italia.org/contribuire/sviluppo/partecipare Pensate che sia meglio inserire nel sito web il link al nuovo documento `operazioni preliminari`?

2019-03-11 09:31 UTC, eLBati commented on sviluppo/come_contribuire.rst
> +Attenzione, il nome del branch dovrebbe avere come prefisso sempre il numero della versione Odoo.
Pensi sia comunque consigliabile per identificare meglio i branch. In tal caso lo scriverei, `per identificare meglio i branch...`

2019-03-11 09:35 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +Supponi ad esempio di aver scovato un bug in uno dei moduli italiani e di voler proporre una correzione.
> rimaneggiandola un po'.

@mymage come?

2019-03-11 10:25 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +* CLA BOT per verificare la stato della tua `CLA <https://odoo-community.org/page/cla>`_
> L'operazione di firmare la CLA è già stata inserita su https://www.odoo-italia.org/contribuire/sviluppo/partecipare Pensate che sia meglio inserire nel sito web solo il link al nuovo documento `operazioni preliminari`?

No secondo me dal sito è bene poter accedere a tutta la procedura per contribuire

2019-03-11 10:31 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +* CLA BOT per verificare la stato della tua `CLA <https://odoo-community.org/page/cla>`_
Ok. Saresti comunque per creare un documento solo per le operazioni preliminari così come suggerito da @mymage?

2019-03-11 10:47 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +* CLA BOT per verificare la stato della tua `CLA <https://odoo-community.org/page/cla>`_
@tafaRU non mi è chiaro cosa ci sarebbe di preciso in questo documento e perché andrebbe estratto da qui.
Nel senso: se sono operazioni preliminari solo per la creazione di una PR è meglio che stiano solo qui

2019-03-12 06:54 UTC, mymage commented on sviluppo/come_contribuire.rst
> +Supponi ad esempio di aver scovato un bug in uno dei moduli italiani e di voler proporre una correzione.
@tafaRU Ecco il testo rivisto secondo me:

Una PR è il modo per comunicare che abbiamo apportato (o abbiamo iniziato a lavorare su) delle modifiche che vorremmo venissero incluse nel progetto. 
Le issue vengono utilizzate per segnalare task, bug o feature di un progetto. 

Prima di creare una nuova PR o issue controllare sempre se ci sono segnalazioni su ciò che si vuole modificare, così da evitare di sovrapporsi ad altre PR e di includere eventuali issue.

Supponi ad esempio di aver scovato un bug in uno dei moduli italiani e di voler proporre una correzione. Vediamo quali sono i passi che dovrai seguire.

2019-03-24 10:49 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +Fork del repository
Non mi vorrei però perdere le ancore ai sottotitoli e i sottomenu creati in automatico durante la generazione delle pagine `html`. Posso però aggiungere un elenco numerato all'inizio come fatto da @SimoRubi [qui](https://github.com/odoo-italia/documentazione/blob/master/sviluppo/review.rst) con i link ai sottotitoli. Che ne pensate?
Per il resto dovrei aver sistemato tutto.

2019-04-20 09:51 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +Fork del repository
@SimoRubi @mymage potete rispondere al mio precedente commento? Grazie.

2019-04-20 10:46 UTC, mymage commented on sviluppo/come_contribuire.rst
> +Fork del repository
Sicuramente un elenco iniziale con i passi è utile. Ho dato un'occhiata e mi sembra tutto ok. L'unica cosa che farei se possibile una leggera cornice intorno alle immagini.

2019-04-23 07:42 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +Fork del repository
@tafaRU in https://github.com/odoo-italia/documentazione/blob/master/sviluppo/review.rst l'ho fatto perché i capitoletti linkati sono lunghi diverse righe e con immagini ecc, quindi la userei come soluzione per i capitoli più lunghi.
Nel tuo caso ci sono capitoli contenenti una/due righe e mi sembra una soluzione dispersiva.

Secondo me sarebbe più diretto un elenco dove le operazioni immediate sono spiegate all'interno dell'elenco, mentre quelle più lunghe rimandano ad un capitoletto apposito.
I link generati da Sphinx li vedo utili appunto per le operazioni più lunghe ma non molto per le operazioni immediate (serve davvero un link ad un capitolo che dice solo di fare `git clone`?)

2019-05-15 13:26 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +Fork del repository
@mymage ho aggiunto la cornice intorno alle immagini
@SimoRubi ho aggiunto l'elenco dei passaggi chiave e accorpato le operazioni di Fork e Clone.
Il resto lo lascerei così.

2019-05-16 06:56 UTC, eLBati commented on sviluppo/come_contribuire.rst
> +una vera e propria conversazione in stile social, in cui potrai discutere insieme ai vari reviewer.
Su github vedo così

![image](https://user-images.githubusercontent.com/1033131/57832624-64c79500-77b8-11e9-9256-96ce1a8f9309.png)

Nella build sphinx invece risulta corretto?

2019-05-16 07:22 UTC, eLBati commented
@tafaRU puoi risolvere il conflitto?

2019-05-16 07:40 UTC, tafaRU commented
> @tafaRU puoi risolvere il conflitto?

ho appena fatto rebase.

2019-05-16 08:15 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +una vera e propria conversazione in stile social, in cui potrai discutere insieme ai vari reviewer.
Sì! Vedi immagine allegata.
![Peek 16-05-2019 10-11](https://user-images.githubusercontent.com/3512779/57837449-21265880-77c3-11e9-945f-212aa5ae3d3b.gif)

2019-05-16 08:22 UTC, eLBati commented
Aspettiamo via di libera di @SimoRubi per il merge

2019-05-16 08:39 UTC, primes2h requested changes
Ho dato un'occhiata al volo, dopo questa piccola modifica direi che è ok!
A suo tempo è stata testata a livello funzionale da Marcelo, ha detto che va bene.  :+1: 

Un'ultima nota generale riguardo lo stile adottato di rivolgersi all'utente.
Per questi tipi di guide direi che può anche andare, in generale però è sempre meglio mantenere l'impersonale.

2019-05-16 08:39 UTC, primes2h commented on sviluppo/come_contribuire.rst
> +#. Fare accettare la PR -> `Fare accettare la PR`_.
Giusto una finezza,
s/Fare/Far

È più leggibile/scorrevole

2019-05-16 08:39 UTC, primes2h commented on sviluppo/come_contribuire.rst
> +Fare accettare la PR
Anche qui come sopra

2019-05-16 08:50 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +#. Fare accettare la PR -> `Fare accettare la PR`_.
Fatto, vedi [diff](https://github.com/odoo-italia/documentazione/compare/31262ac9351ec3dfaa989d0459a4f08ac7d20be8..4160670a75f8e914f8e3b9a99cf6714a7e503672).

2019-05-16 08:50 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +Fare accettare la PR
Fatto, vedi [diff](https://github.com/odoo-italia/documentazione/compare/31262ac9351ec3dfaa989d0459a4f08ac7d20be8..4160670a75f8e914f8e3b9a99cf6714a7e503672).

2019-05-20 09:11 UTC, SimoRubi approved these changes
Per me ok

2019-05-20 09:11 UTC, SimoRubi commented on sviluppo/come_contribuire.rst
> +#. Operazioni preliminari -> `Operazioni preliminari`_.
(Anche per i punti sotto)
La parte prima della `->` dovrebbe spiegare brevemente cosa c'è nel capitolo, mettere proprio le stesse parole mi pare ridondante, ma forse è solo questione di gusti.

2019-05-20 09:17 UTC, tafaRU commented
@primes2h per te è ok?

2019-05-20 14:16 UTC, primes2h commented on sviluppo/come_contribuire.rst
> +#. Operazioni preliminari -> `Operazioni preliminari`_.
Concordo sulla ridondanza.

Eventualmente, per semplificare ulteriormente, si potrebbe mettere il link direttamente sul primo testo, eliminando del tutto "->" e quello che viene dopo.

2019-05-24 07:23 UTC, tafaRU commented on sviluppo/come_contribuire.rst
> +#. Operazioni preliminari -> `Operazioni preliminari`_.
@primes2h, ho messo il link direttamente sul testo. Puoi aggiornare la tua review?

2019-05-24 08:03 UTC, primes2h approved these changes

2019-05-24 08:04 UTC, primes2h commented on sviluppo/come_contribuire.rst
> +#. Operazioni preliminari -> `Operazioni preliminari`_.
:+1:

2019-05-25 08:56 UTC, merged