Add doc layout
odoo-italia/documentazione pull request #6
Opened 2019-04-07 15:54 UTC by primes2h

2019-04-21 06:14 UTC, eLBati requested changes
Rimuoverei i file `pyc` e aggiungerei il `.gitignore`

Provando a fare la build ottengo

```
sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html
/home/elbati/workspace/odoo/doc/odoo-italia-doc/_extensions/exercise_admonition.py:24: RemovedInSphinx30Warning: sphinx.locale.l_() is deprecated.  Please use `_()` instead.
  admonitionlabels['exercise'] = l_('Exercise')
/home/elbati/workspace/odoo/doc/odoo-italia-doc/README.rst: WARNING: document isn't included in any toctree
/home/elbati/workspace/odoo/doc/odoo-italia-doc/guide/overview.rst: WARNING: document isn't included in any toctree
/home/elbati/workspace/odoo/doc/odoo-italia-doc/promozione/overview.rst: WARNING: document isn't included in any toctree
/home/elbati/workspace/odoo/doc/odoo-italia-doc/sviluppo/overview.rst: WARNING: document isn't included in any toctree
/home/elbati/workspace/odoo/doc/odoo-italia-doc/test/overview.rst: WARNING: document isn't included in any toctree
/home/elbati/workspace/odoo/doc/odoo-italia-doc/traduzioni/overview.rst: WARNING: document isn't included in any toctree
/home/elbati/workspace/odoo/doc/odoo-italia-doc/web/overview.rst: WARNING: document isn't included in any toctree
/home/elbati/workspace/odoo/doc/odoo-italia-doc/test.rst: WARNING: self referenced toctree found. Ignored.
/home/elbati/workspace/odoo/doc/odoo-italia-doc/traduzioni.rst: WARNING: self referenced toctree found. Ignored.
/home/elbati/workspace/odoo/doc/odoo-italia-doc/documentazione.rst: WARNING: self referenced toctree found. Ignored.
/home/elbati/workspace/odoo/doc/odoo-italia-doc/promozione.rst: WARNING: self referenced toctree found. Ignored.
/home/elbati/workspace/odoo/doc/odoo-italia-doc/web.rst: WARNING: self referenced toctree found. Ignored.
/home/elbati/workspace/odoo/doc/odoo-italia-doc/guide.rst: WARNING: self referenced toctree found. Ignored.

Exception occurred:
  File "/home/elbati/workspace/odoo/doc/odoo-italia-doc/_extensions/odooitalia_ext/translator.py", line 60, in __init__
    self.highlightlang = self.highlightlang_base = self.builder.config.highlight_language
AttributeError: 'document' object has no attribute 'config'
The full traceback has been saved in /tmp/sphinx-err-re9doa5e.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:52: recipe for target 'html' failed
make: *** [html] Error 2
```

Allego `/tmp/sphinx-err-re9doa5e.log`
[sphinx-err-re9doa5e.log](https://github.com/odoo-italia/documentazione/files/3100967/sphinx-err-re9doa5e.log)

2019-04-21 09:59 UTC, primes2h commented
> Rimuoverei i file `pyc` e aggiungerei il `.gitignore`

Ops, mi sono scordato di farlo.
Adesso è ok.

> Provando a fare la build ottengo
> 
> ```
> sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/_extensions/exercise_admonition.py:24: RemovedInSphinx30Warning: sphinx.locale.l_() is deprecated.  Please use `_()` instead.
>   admonitionlabels['exercise'] = l_('Exercise')
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/README.rst: WARNING: document isn't included in any toctree
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/guide/overview.rst: WARNING: document isn't included in any toctree
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/promozione/overview.rst: WARNING: document isn't included in any toctree
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/sviluppo/overview.rst: WARNING: document isn't included in any toctree
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/test/overview.rst: WARNING: document isn't included in any toctree
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/traduzioni/overview.rst: WARNING: document isn't included in any toctree
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/web/overview.rst: WARNING: document isn't included in any toctree
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/test.rst: WARNING: self referenced toctree found. Ignored.
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/traduzioni.rst: WARNING: self referenced toctree found. Ignored.
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/documentazione.rst: WARNING: self referenced toctree found. Ignored.
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/promozione.rst: WARNING: self referenced toctree found. Ignored.
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/web.rst: WARNING: self referenced toctree found. Ignored.
> /home/elbati/workspace/odoo/doc/odoo-italia-doc/guide.rst: WARNING: self referenced toctree found. Ignored.
> 
> Exception occurred:
>   File "/home/elbati/workspace/odoo/doc/odoo-italia-doc/_extensions/odooitalia_ext/translator.py", line 60, in __init__
>     self.highlightlang = self.highlightlang_base = self.builder.config.highlight_language
> AttributeError: 'document' object has no attribute 'config'
> The full traceback has been saved in /tmp/sphinx-err-re9doa5e.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> Makefile:52: recipe for target 'html' failed
> make: *** [html] Error 2
> ```
> 
> Allego `/tmp/sphinx-err-re9doa5e.log`
> [sphinx-err-re9doa5e.log](https://github.com/odoo-italia/documentazione/files/3100967/sphinx-err-re9doa5e.log)

I warning sono normali, provo a indagare sull'errore.

2019-04-21 10:04 UTC, primes2h commented
> I warning sono normali, provo a indagare sull'errore.

Mi viene in mente che forse potrebbero essere legati alla cache che adesso è stata rimossa.
Prova a rifare il build.

2019-04-21 15:28 UTC, marcelofrare commented
impostando il branch add_doc_layout anche a me compare l'errore AttributeError: 'document' object has no attribute 'config' (allego log)

[sphinx-err-5mhhmztg.log](https://github.com/odoo-italia/documentazione/files/3101339/sphinx-err-5mhhmztg.log)

ho fatto:
make clean
make html

2019-04-21 17:51 UTC, primes2h commented
Entrambi usate la versione 2.0.1 di sphinx, ho verificato che il build va a buon fine con una versione < 2
es. io ho usato una 1.8.5.

Ho anche verificato che la versione minima necessaria è la 1.4.2, ho aggiornato il file conf.py.

2019-04-21 19:16 UTC, marcelofrare commented
installando la versione 1.8.5 di sphinx, funziona!

2019-04-23 15:04 UTC, eLBati commented
Ok, usando la `1.8.5` riesco a fare la build. Sarebbe da documentare.

Per il resto ottimo, carico su https://www.odoo-italia.org/documentazione ?

2019-04-23 15:12 UTC, primes2h commented
> Ok, usando la `1.8.5` riesco a fare la build. Sarebbe da documentare.
> 
> Per il resto ottimo, carico su https://www.odoo-italia.org/documentazione ?

Prima di caricare ci sarebbe da fare:
1) una review di questa PR riguardo al contenuto/layout/funzionamento della pagina (es. i menù, intestazioni e piè di pagina, css dei testi ecc.). Io l'ho abbozzato, è da provare/migliorare.
2) dopo aver fatto il merge, provare alcuni documenti con la nuova struttura.

2019-04-23 21:06 UTC, eLBati approved these changes

2019-04-29 08:35 UTC, primes2h commented
Ho scoperto che anche openeducat usa lo stesso tema per la documentazione, personalizzato.

https://doc.openeducat.org/

2019-04-29 09:38 UTC, primes2h commented
> Ok, usando la `1.8.5` riesco a fare la build. Sarebbe da documentare.

Fatto in https://github.com/odoo-italia/documentazione/pull/6/commits/ff6e777879f99c505321743113985f383c2a5637

2019-04-30 15:22 UTC, eLBati commented
:+1:

2019-05-16 07:21 UTC, merged

2019-05-16 08:58 UTC, primes2h commented
Prima di spostare la documentazione nel sito mancherebbe una pagina standard di WIP per la sezioni vuote, è quasi pronta.

2019-05-16 09:06 UTC, tafaRU commented
> una pagina standard di WIP per la sezioni vuote, è quasi pronta.

:+1: 

Non sarebbe male riuscire a pubblicarla sul sito prima dello [sprint di Napoli](https://www.odoo-italia.org/event/code-sprint-2019-06-05-2019-06-07-1) in modo da poterla usare come materiale per introdurre i newbie!

2019-05-16 09:22 UTC, eLBati commented
> Non sarebbe male riuscire a pubblicarla sul sito prima dello sprint di Napoli in modo da poterla usare come materiale per introdurre i newbie

Esatto

2019-05-21 13:56 UTC, primes2h commented
> > Non sarebbe male riuscire a pubblicarla sul sito prima dello sprint di Napoli in modo da poterla usare come materiale per introdurre i newbie
> 
> Esatto

Ecco la PR #8 !